# Generate an sbom for the cartservice

permissions:
  contents: read
  packages: write

name: Cartservice SBOM
'on':
  workflow_dispatch: {}
  push: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: 5.x
      - id: determine_version
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.14
        with:
          additionalArguments: /overrideconfig mode=Mainline
      - name: Install Octopus Deploy CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: latest
      - name: Set up DotNET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build SBOM
        run: docker run -v $PWD:/app cyclonedx/cyclonedx-dotnet /app -o /app
        working-directory: src/cartservice
      - name: Build SBOM package
        run: >
          octo pack
          --id cartservice-sbom
          --version ${{ steps.determine_version.outputs.semVer }}
          --format zip
          --include **/bom.xml
        shell: bash
        working-directory: src/cartservice
      - name: Publish SBOM file
        run: >
          mvn deploy:deploy-file
          --batch-mode
          -Dfile=adservice-sbom.${{ steps.determine_version.outputs.semVer }}.zip
          -Durl="https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@maven.pkg.github.com/${{ github.repository }}"
          -DgroupId=microservices-demo
          -DartifactId=cartservice-sbom
          -Dversion=${{ steps.determine_version.outputs.semVer }}
          -Dpackaging=zip
        shell: bash
        working-directory: src/cartservice