# This workflow builds and pushes images to the octopussamples DockerHub organization.

name: Payment Service Docker Build
'on':
  workflow_dispatch: {}
  push:
    paths:
      - 'src/paymentservice/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Install Octopus Deploy CLI
        uses: OctopusDeploy/install-octopus-cli-action@v1
        with:
          version: latest
      - id: fixed_branch_name
        name: Create branch name
        run: |
          BRANCH_NAME=${{ github.event.ref }}
          BRANCH_NAME=${BRANCH_NAME#refs/heads/}
          FIXED_BRANCH_NAME=${BRANCH_NAME//[^a-zA-Z0-9-]/-} 
          echo "fixedbranch=$FIXED_BRANCH_NAME" >> $GITHUB_ENV
        shell: bash
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_SAMPLES_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SAMPLES_PASSWORD }}
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.14
        with:
          versionSpec: 5.x
      - id: determine_version
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.14
        with:
          additionalArguments: /overrideconfig mode=Mainline
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:src/paymentservice"
          push: true
          tags: octopussamples/paymentservice:${{ steps.determine_version.outputs.semVer }}
      - name: Create Mainline Octopus Release
        if: github.ref == 'refs/heads/main'
        uses: OctopusDeploy/create-release-action@v1
        with:
          api_key: ${{ secrets.OCTOPUS_APIKEY }}
          space: ${{ secrets.OCTOPUS_SPACE }}
          project: Payment Service
          channel: Mainline
          server: ${{ secrets.OCTOPUS_SERVER }}
          deploy_to: Development
          packages: ${{ steps.determine_version.outputs.semVer }}
      - name: Create Branch Octopus Release
        if: github.ref != 'refs/heads/main'
        uses: OctopusDeploy/create-release-action@v1
        with:
          api_key: ${{ secrets.OCTOPUS_APIKEY }}
          space: ${{ secrets.OCTOPUS_SPACE }}
          project: Email Service
          channel: ${{ env.fixedbranch }}
          server: ${{ secrets.OCTOPUS_SERVER }}
          deploy_to: Payment Service
          packages: ${{ steps.determine_version.outputs.semVer }}